### ISSUE TITLE
How to maintain a continuous rotation state before requesting？

### ISSUE THREAD

**Issue by wscart** [TheBlindHawk/Roulette#17]
Hello, there is a question about how to cooperate with the request and how to implement a method to keep it spinning before the request returns?

**Comment by TheBlindHawk** [comment]
Hello, sorry for the (very) late reply!
I am afraid I still do not have such a functionality, but I'll add it as something to implement.

Given the current functionalities, if you can somewhat foresee how long the request will take the best solution would be to change the duration of the spin accordingly.
But I'm guessing the result you want to show probably comes with the request, so the roulette would need to be spinnable without a determined result.

I'm guessing what I need to implement is something like this?
```
roulette.beginEmptySpin();
axios.get(...).then((res)=>{
  roulette.roll(res.data.spin_to_here);
}))
```
I'll set it as a 3.1 objective.

**Comment by TheBlindHawk** [comment]
@wscart 
I added an async function to let the roulette roll while waiting for a promise.
You can use it like so:
```typescript
const { promise, resolve, reject } = Promise.withResolvers()

roulette.asyncRollByIndex(promise)

// keeps rolling while waiting for the value
axios.get('your_path').then((res) => {
  resolve(res.data.rollIndex)
}).catch((error) => {
  reject(error)
})
```

PS: I just noticed the audio is not working for the asyncRoll, I will try to add it for 3.1.1
